services:

  couchdb:
    container_name: couchdb
    image: apache/couchdb:2.3
    restart: always
    ports:
      - 5984:5984
    volumes:
      - couchdb_data:/opt/couchdb/data
    environment:
      - 'COUCHDB_USER=admin'
      - 'COUCHDB_PASSWORD=password'
    networks:
      - private

  jupyter:
    build: ./docker/jupyter
    image: jupyter_ansible
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.password=sha1:58eaa2e688ae:11fd96685b9203d1256a1e09603c9be4f62c94b6
    volumes:
      # - jupyter_data:/home/ansible
      - ./notebooks:/code
    environment:
      - 'JUPYTER_PASSWORD=sha1:58eaa2e688ae:11fd96685b9203d1256a1e09603c9be4f62c94b6'
      - USER=student001
    ports:
      - 8888:8888
    networks:
      - private

  ubuntu:
    build: ./docker/ubuntu
    image: ubuntu_ssh
    networks:
      - private

volumes:
  couchdb_data:
  # jupyter_data:

networks:
  private:
