version: '3.2'

services:

  couchdb:
    container_name: couchdb
    image: apache/couchdb:2.3
    restart: always
    ports:
      - 5984:5984
    volumes:
      - ./couchdb/data:/opt/couchdb/data
    environment:
      - 'COUCHDB_USER=admin'
      - 'COUCHDB_PASSWORD=password'
    networks:
      - private

  jupyter:
    build: ./docker/jupyter
    image: jupyter_ansible
    volumes:
      # - jupyter_data:/home/ansible
      - ./notebooks:/home/ansible
    ports:
      - 8888:8888
    networks:
      - private

  ubuntu:
    build: ./docker/ubuntu
    image: ubuntu_ssh
    networks:
      - private

# volumes:
#   jupyter_data:

networks:
  private:
