---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    people:
    - name: Mike
      epic: true
      kantoor: Eindhoven
      status:
        kleur: blauw
        ready: true
    - name: John
      epic: false
      kantoor: Utrecht
      status:
        kleur: groen
        ready: true
    - name: Betty
      epic: true
      kantoor: Nijmegen
      status:
        kleur: rood
        ready: true
    - name: Allan
      epic: true
      kantoor: Groningen
      status:
        kleur: oranje
        ready: true

  tasks:
    - name: FIND PEOPLE
      debug: msg="Yay it's {{ item.name }} from {{ item.kantoor}} and is ready {{ item.status.ready }}"
      with_items: "{{ people }}"
      when: item.epic
