---
- name: SHOW DICTIONARY
  debug:
    msg: "DICT LOOKUP: {{ lookup('dict', bla) }}"


- name: PRINT PHONE RECORDS
  debug:
    msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
  loop: "{{ lookup('dict', users_orig) }}"


- name: PRINT DYNAMIC PHONE RECORDS
  debug:
    msg: "User {{ item.key }} is {{ item.name }} ({{ item.telephone }})"
  loop: "{{ users }}"


- name: CREATING USER ACCOUNTS
  user:
    name: "{{ item.key }}"
    state: "{{ item.state }}"
    # remove: yes
  loop: "{{ users }}"
